spring.application.name=andensemesterProeve_theSemicolons
spring.datasource.url=jdbc:mysql://87.57.243.106:33306/DeckForge
spring.datasource.username=amaliegp
spring.datasource.password=PhoneHologramHelium1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never

spring.thymeleaf.cache=false

server.port=8080